### ISSUE TITLE
Update dead links

### ISSUE THREAD

**Issue by zhengqunkoo** [rumpkernel/wiki#10]
Some links in the README link to https://rumpkernel.org. It looks like a SEO website. Links should point to https://github.com/rumpkernel/wiki/wiki instead.
![image](https://user-images.githubusercontent.com/13476560/158102068-7e4ea1a0-afb8-418b-b5e8-d2975b7ca7af.png)

**Comment by lukem** [comment]
I 👍 the request for change, not the SEO takeover...

**Comment by anttikantee** [comment]
It's a wiki and anyone can change it?

If someone has trouble bulk-editing links -- I recommend downloading the wiki and running perl over it -- let me know.

**Comment by lukem** [comment]
I tried an edit of the wiki.wiki.git checkout but I couldn't push even when changing the URI to a usual git@github link (no perms). So I just manually edited where I could. See pull request #11 for some more fixes, and issue #12 for remaining stuff I can't easily fix.

**Comment by anttikantee** [comment]
You might have push perms to the wiki now (clicking the right privs buttons is always an adventure).
