### ISSUE TITLE
fix remaining links to old site

### ISSUE THREAD

**Issue by lukem** [rumpkernel/wiki#12]
I've fixed various links to now point to github instead of the old site (rumpkernel dot org) per issue #10.

There are some remaining links that need someone with project write privileges to resolve:

1. https://github.com/rumpkernel
    1. change project link `http://rumpkernel.org` to `https://github.com/rumpkernel`
1. https://raw.githubusercontent.com/wiki/rumpkernel/wiki/FAQ.in
    1. change `http://wiki.rumpkernel.org` to `https://github.com/rumpkernel/wiki/wiki`
    2. change `book.rumpkernel.org` to ???
    3. change `donations@rumpkernel.org` to ???
    4. change `http://repo.rumpkernel.org` to `https://github.com/rumpkernel/`
    5. change `http://rumpkernel.org/contrib.html` to `https://github.com/rumpkernel/wiki/wiki/Info%3A-Contribution-guidelines`
    6. regenerate Info:-FAQ using `makefaq.sh`.
1. other references to `book.rumpkernel.org` to fix to ???
    1. https://github.com/rumpkernel/wiki/wiki/Info%3A-Publications-and-Talks
    1. https://github.com/rumpkernel/wiki/wiki/Tutorial:-Getting-Started

**Comment by anttikantee** [comment]
The website should probably be rumpkernel.github.io (but the CNAME in that repo needs to be removed).

The book url is http://www.fixup.fi/misc/rumpkernel-book/ (I'm "working" on updating the latest edition to not contain rumpkernel.org links, should be done any year now).

The donations stuff can be removed.

I'm getting a complaint that the github ssh key has changed, so I'll have to look into it before I can fix the website.

**Comment by anttikantee** [comment]
Ok, that should be it for the website and email addresses.

**Comment by lukem** [comment]
I've changed the "home page" links (that I changed from rumpkernel.org to github.com/rumpkernel) to https://rumpkernel.github.io

**Comment by lukem** [comment]
After @anttikantee gave me commit privs to the wiki backend, I've fixed:
- item 2: the FAQ
- item 3: the book links per the comment earlier

and item 1 was done by @anttikantee 

This issue should be fixed now.

**Comment by anttikantee** [comment]
thanks!
