### ISSUE TITLE
Can't reach the wiki of Rumpkernel

### ISSUE THREAD

**Issue by p-jacquot** [rumpkernel/wiki#9]
Hello,

I hope my issue isn't stupid. I'm new to the world of Unikernels, and I discovered Rump a few days ago.

I would like to read your documentation to use Rumpkernel, but I can't reach the following URL : [http://wiki.rumpkernel.org/](http://wiki.rumpkernel.org/).

Is your wiki down, or elsewhere ?

**Comment by kaveman-** [comment]
while the site/domain seems to be gone, this repo is the wiki. checkout the [wiki](https://github.com/rumpkernel/wiki/wiki)

**Comment by p-jacquot** [comment]
Okay, thank you very much !
